
package vista;

import modelo.operacion;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JTextArea;

public class historial_operaciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form historial_operaciones
     */
    public historial_operaciones() {
        initComponents();
        cargarHistorial();
    }
    
    private void cargarHistorial() {
        StringBuilder sb = new StringBuilder();
        try (BufferedReader lector = new BufferedReader(new FileReader("bitacoraCalculadora.txt"))) {
            String linea;
            while ((linea = lector.readLine()) != null) {
                sb.append(linea).append(System.lineSeparator());
            }
        } catch (IOException excepcion) {
            excepcion.printStackTrace();
        }
        txt_mostrar.setText(sb.toString());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_historial = new javax.swing.JScrollPane();
        txt_mostrar = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("BitacoraCalculadora.txt");
        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(353, 415));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        txt_mostrar.setColumns(20);
        txt_mostrar.setRows(5);
        panel_historial.setViewportView(txt_mostrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_historial, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_historial, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("BitacoraCalculadora.txt");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane panel_historial;
    private javax.swing.JTextArea txt_mostrar;
    // End of variables declaration//GEN-END:variables
}
