/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

/**
 *
 * @author robin
 */
public class Manual extends javax.swing.JInternalFrame {

    /**
     * Creates new form Manual
     */
    public Manual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt_manual = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setForeground(new java.awt.Color(51, 204, 0));
        setIconifiable(true);
        setResizable(true);
        setTitle("BitacoraCalculadora.txt ");
        setAutoscrolls(true);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(false);

        txt_manual.setColumns(20);
        txt_manual.setRows(5);
        txt_manual.setText("Operaciones Básicas\nSumar:\n\nIntroduce el primer número.\nPresiona el botón +.\nIntroduce el segundo número.\nPresiona el botón = para ver el resultado.\nRestar:\n\nIntroduce el primer número.\nPresiona el botón -.\nIntroduce el segundo número.\nPresiona el botón = para ver el resultado.\nMultiplicar:\n\nIntroduce el primer número.\nPresiona el botón *.\nIntroduce el segundo número.\nPresiona el botón = para ver el resultado.\nDividir:\n\nIntroduce el primer número.\nPresiona el botón /.\nIntroduce el segundo número.\nPresiona el botón = para ver el resultado.\n3. Historial de Operaciones\nVer Historial:\nHaz clic en el botón \"Historial\" en la interfaz de la \ncalculadora.\nAparecerá una ventana con  las operaciones \nrealizadas recientemente.\n4. Reiniciar la Calculadora\nPaso 1: Presiona en donde dice Opciones el cual\nte desplegara dos opciones (NUEVO y Historial)\nselecciona NUEVO para borrar la pantalla y reiniciar\nla calculadora.\n5. Cerrar la Aplicación\nPaso 1: Haz clic en la \"X\" en la esquina superior \nderecha  de la ventana de la calculadora.\nPaso 2: La aplicación se cerrará.");
        jScrollPane1.setViewportView(txt_manual);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt_manual;
    // End of variables declaration//GEN-END:variables
}
